---
title: "Functional Embedding"
---

```{r}
library(lubridate)
library(tidyverse)
library(here)
library(corrr)
library(tidygraph)
library(uwot)
library(dbscan)
library(xgboost)
library(rsample)
library(caret)
library(ggrepel)
library(patchwork)
library(clipr)
library(ggnewscale)
library(ggpointdensity)
```

```{r functions}
load_scaled_effects <- function(file = '19Q4_Achilles_gene_effect_tenative.csv', 
                                filter_cells = c()) {
  # load gene effects and scale (z-score) each gene
  gene_effects <- read_csv(here('data',file)) %>%
    rename(DepMap_ID = X1) %>%
    select_if(~ !any(is.na(.))) %>%
    filter(!(DepMap_ID %in% filter_cells))
  scaled_effects <- gene_effects %>%
    column_to_rownames('DepMap_ID') %>%
    scale()
  return(scaled_effects)
}

calculate_embedding <- function(feature_matrix, n_neighbors = 8, 
                                metric = 'cosine') {
  curr_embedding <- umap(feature_matrix, 
                         verbose = T, n_threads = 8, scale = F,
                         n_neighbors = n_neighbors, metric = metric)
  colnames(curr_embedding) <- c('UMAP_1', 'UMAP_2')
  embedding_tibble <- curr_embedding %>%
    as_tibble() %>%
    mutate(DepMap_ID = row.names(feature_matrix))
  return(embedding_tibble)
}
load_ccle_meta <- function(file = '19Q4_sample_info_tenative.csv') {
  sample_info <- read_csv(here('data', file)) %>%
    mutate(stripped_cell_line_name = word(CCLE_name, sep = '_'))
}
plot_embedding <- function(embedding_tibble, color_col, ...) {
  p <- ggplot(embedding_tibble, aes(x = UMAP_1, y = UMAP_2,  
                               color = !!as.name(color_col))) +
    geom_point(...) +
    theme_classic() +
    theme(aspect.ratio = 1) 
  return(p)
}
generate_louvain_clusters <- function(feature_matrix, n_neighbor = 5) {
  # feature matrix with rows as samples and columns as features
  # will cluster rows using the louvain clustering algorithm
  transposed_matrix <- t(feature_matrix)
  top_cell_cors <- transposed_matrix %>%
    correlate() %>%
    stretch() %>%
    group_by(x) %>%
    top_n(n_neighbor, r)
  cell_graph <- top_cell_cors %>%
    as_tbl_graph(directed = F) %>%
    activate(nodes) %>%
    mutate(cluster = group_louvain(weights = r))
  cell_cluster <- cell_graph %>%
    as_tibble() %>%
    rename(DepMap_ID = name) %>%
    mutate(as.factor(cluster))
  return(cell_cluster)
}
generate_dense_clusters <- function(feature_matrix) {
  # use umap and hdbscan to identify clusters
  hd_embedding <- umap(feature_matrix, n_components = 10,
                       verbose = T, n_threads = 8, scale = F,
                       n_neighbors = 30, metric = 'cosine', 
                       min_dist = 0)
  clustering <- hdbscan(hd_embedding, minPts = 5)
  cluster_tib <- tibble(cluster = as.factor(clustering$cluster), 
                        DepMap_ID = rownames(feature_matrix))
  return(cluster_tib)
}
load_ccle_features <- function() {
  expression <- read_csv(here('data', 'CCLE','tidy_model_mats', 'expression.csv'))
  fusions <- read_csv(here('data','CCLE', 'tidy_model_mats','fusions.csv'))
  methylation <- read_csv(here('data','CCLE', 'tidy_model_mats', 'methylation.csv'))
  mutations <- read_csv(here('data','CCLE', 'tidy_model_mats', 'mutations.csv'))
  copy_number <- read_csv(here('data', 'CCLE', 'tidy_model_mats', 'copy_number.csv'))
  bound_features <- bind_rows(expression, fusions, methylation, mutations, copy_number)
  return(bound_features)
}
calculate_cluster_enrichment <- function(feature_matrix, clusters) {
  # feature matrix has genes as columns and sample ID's as rows
  median_scaled_effects <- feature_matrix %>%
    as.data.frame() %>%
    rownames_to_column('DepMap_ID') %>%
    gather(gene, scaled_effect, -DepMap_ID) %>%
    inner_join(clusters) %>%
    group_by(cluster, gene) %>%
    summarise(median_scaled_effect = median(scaled_effect), 
              n = n())
  return(median_scaled_effects)
}
validate_dependency <- function(model_matrix, cluster_tib) {
  cv_results <- list()
  for(curr_cluster in unique(cluster_tib$cluster)) {
    print(curr_cluster)
    cluster_cells <- cluster_tib %>%
      filter(cluster == curr_cluster) %>%
      select(DepMap_ID) %>%
      unlist() %>%
      as.character()
    y <- as.numeric(row.names(model_matrix) %in% cluster_cells)
    flds <- createFolds(as.factor(y), k = 3)
    xgb_cv <- xgb.cv(params = list(nthread = 8, 
                                   objective = 'binary:logistic', alpha = 0.05), 
                     data = model_matrix, 
                     nrounds = 10, label = y, 
                     metrics = c('error', 'rmse', 'logloss', 'auc'),  
                     verbose = FALSE, folds = flds)
    best_iteration <- xgb_cv$evaluation_log %>%
      as_tibble() %>%
      top_n(1, test_auc_mean) %>%
      top_n(1, test_rmse_mean) %>%

      mutate(cluster = curr_cluster)
    cv_results[[curr_cluster]] <- best_iteration
    gc()
  }
  return(bind_rows(cv_results))
}

validate_ccle <- function(gene_enrichmet, cluster_tib, 
                              ccle_features, n_genes = 100) {
  cluster_top_genes <- gene_enrichmet %>%
    group_by(cluster) %>%
    top_n(n_genes, abs(median_scaled_effect)) %>%
    arrange(cluster, median_scaled_effect)
  cv_results <- list()
  for(curr_cluster in unique(cluster_tib$cluster)) {
    print(curr_cluster)
    curr_top_genes <- cluster_top_genes %>%
      ungroup() %>%
      filter(cluster == curr_cluster) %>%
      select(gene) %>%
      unlist() %>%
      word(1,1)
    spread_features <- ccle_features %>%
      filter(gene %in% curr_top_genes) %>%
      select(-gene) %>%
      mutate(feature_name = paste0(feature, '_', source)) %>%
      select(-source, -feature) %>%
      distinct() %>% 
      spread(feature_name, value)
    cluster_cells <- cluster_tib %>%
      filter(cluster == curr_cluster) %>%
      select(DepMap_ID) %>%
      unlist() %>%
      as.character()
    model_tibble <- spread_features %>%
        mutate(member = as.numeric(DepMap_ID %in% cluster_cells)) %>%
        select(-DepMap_ID)
    model_matrix <- model_tibble %>%
        select(-member) %>%
        as.matrix()
    flds <- createFolds(as.factor(model_tibble$member), k = 3)
    xgb_cv <- xgb.cv(params = list(nthread = 8, 
                    objective = 'binary:logistic', alpha = 0.05), 
                    data = model_matrix, 
                    nrounds = 10, label = model_tibble$member, 
                    metrics = c('error', 'rmse', 'logloss', 'auc'),  
                    verbose = FALSE, folds = flds)
    best_iteration <- xgb_cv$evaluation_log %>%
      as_tibble() %>%
      top_n(1, test_auc_mean) %>%
      top_n(1, test_rmse_mean) %>%
      mutate(cluster = curr_cluster)
    cv_results[[curr_cluster]] <- best_iteration
  }
  bound_cv_results <- bind_rows(cv_results)
  return(bound_cv_results)
}

plot_cluster_aucs <- function(clusters, ccle_cv, dependency_cv, label_clusters = c()) {
  cluster_n <- clusters %>%
    group_by(cluster) %>%
    summarise(n = n())
  cluster_summaries <- inner_join(cluster_n, ccle_cv) %>%
    inner_join(dependency_cv, by = 'cluster', suffix = c('_ccle', '_dependency'))
  p <- ggplot(cluster_summaries) +
    aes(x = test_auc_mean_dependency, y = test_auc_mean_ccle) +
    geom_point(aes(size = n), 
               show.legend = F, pch = 16, color = 'skyblue') +
    geom_abline(color = 'grey') +
    geom_text_repel(aes(label = cluster), data = cluster_summaries %>%
                      filter(cluster %in% label_clusters),
                    min.segment.length = 0) +
    theme_classic() +
    theme(aspect.ratio = 1) 
  return(p)
}

get_cluster_summary_plots <- function(clusters, cell_meta, embedding, ccle_cv, dependency_cv) {
  cluster_embedding_meta <- inner_join(clusters, cell_meta) %>%
    inner_join(embedding)
  cluster_tissue_summary <- cluster_embedding_meta %>%
    group_by(cluster, primary_tissue) %>%
    summarise(n = n())
  tidy_cv_results <- inner_join(ccle_cv, dependency_cv,
                                  by = 'cluster', 
                                  suffix = c('_ccle', '_dependency')) %>%
    select(test_auc_mean_ccle, test_auc_mean_dependency, cluster) %>%
    rename(`CCLE AUC` = test_auc_mean_ccle, `Dependency AUC` = test_auc_mean_dependency) %>%
    gather(source, auc, -cluster) %>%
    mutate(source = factor(source, levels = c('Dependency AUC', 'CCLE AUC')))
  summary_plots <- list()
  for(curr_cluster in unique(clusters$cluster)) {
    curr_embedding_data <- cluster_embedding_meta %>%
      mutate(curr_cluster = cluster == curr_cluster)
    embedding_p <- plot_embedding(curr_embedding_data, 'curr_cluster', pch = 16, alpha = 0.49) +
      scale_color_manual(values = c('grey', 'red')) +
      theme(legend.position = '') +
      ggtitle('Embedding')
    cluster_cv <- tidy_cv_results %>% 
      filter(cluster == curr_cluster) 
    cv_p <- ggplot(cluster_cv) +
      aes(x) +
      aes(x = source, y = auc) +
      theme_classic() +
      theme(text = element_text(size = 10),
            axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
      geom_col(fill = '#33a02c', color = 'black') +
      ggtitle('Validation') +
      xlab('') +
      geom_hline(yintercept = 0.5, linetype = 'dashed') +
      ylim(0, 1)
    curr_tissue_summary <- cluster_tissue_summary %>%
      filter(cluster == curr_cluster) %>%
      mutate(primary_tissue = fct_reorder(primary_tissue, n))
    tissue_p <- ggplot(curr_tissue_summary) +
      aes(x = primary_tissue, y = n) +
      theme_classic() +
      theme(text = element_text(size = 10),
            axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
      geom_col(fill = 'skyblue', color = 'black') +
      ggtitle('Tissue') +
      xlab('')
    current_dependencies <- tidy_dependencies %>%
      filter(cluster == curr_cluster) %>%
      top_n(5, abs(median_scaled_effect)) %>%
      mutate(gene = fct_reorder(gene, median_scaled_effect))
    dependency_p <- ggplot(current_dependencies) +
      aes(x = gene, y = median_scaled_effect) +
      theme_classic() +
      theme(text = element_text(size = 10),
            axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
      geom_col(aes(fill = median_scaled_effect), color = 'black', show.legend = F) +
      ggtitle('Dependency') +
      xlab('') +
      ylab('median dependency (Z-score)') +
      geom_hline(yintercept = 0) +
      scale_fill_gradient2()
    summary_p <- ((embedding_p / cv_p) | tissue_p | dependency_p) + 
      plot_annotation(title = paste('Cluster', curr_cluster))
    summary_plots[[curr_cluster]] <- summary_p
  }
  return(summary_plots)
}

load_achilles_meta <- function(file = 'Pooled CRISPR Screening.csv') {
  cell_metainfo <- read_csv(here('data', file)) %>%
      mutate(`Late Harvest Date` = lubridate::mdy(`Late Harvest Date`)) %>%
      mutate(`Late Harvest Date` = if_else(`Late Harvest Date` > lubridate::mdy('1/1/10'), 
                                          `Late Harvest Date`, NULL))
}

load_modifiers <- function(file = 'olivieri_2019_bioarxiv.csv') {
  modifiers <- read_csv(here('data', file))
  gathered_modifiers <- modifiers %>%
    gather(modifier, z_score, -Gene)
  return(gathered_modifiers)
}

load_epigenetic_cp <- function(file = 'CP0036_GRCh38_NCBI_strict_gene_20191021.txt') {
  chip_file <- read_tsv(here('data', file))
  return(chip_file)
}

```

```{r embedding}
scaled_effects <- load_scaled_effects()
embedding <- calculate_embedding(scaled_effects)
ccle_meta <- load_ccle_meta()
embedding_meta <- inner_join(embedding, ccle_meta)
plot_embedding(embedding_meta, 'primary_tissue') +
  theme(legend.position = '')
ggsave(here('figures', paste0(Sys.Date(), '_tis_emdbedding.png')), 
       width = 4, height = 4)
```

```{r clustering}
clusters <- generate_dense_clusters(scaled_effects)
cluster_embedding <- inner_join(clusters, embedding) 
plot_embedding(cluster_embedding, 'cluster')
```

```{r}
ko_enrichment <- calculate_cluster_enrichment(scaled_effects, clusters)
epigenetic_chip <- load_epigenetic_cp()
cluster1_epigenetic_enrichment <- ko_enrichment %>%
  filter(cluster == '1') %>%
  mutate(gene = word(gene, 1, 1), 
         CP0036 = gene %in% epigenetic_chip$`Gene Symbol`, 
         type = if_else(CP0036, 'CP0036', 'Other'))  
ggplot(cluster1_epigenetic_enrichment) +
  aes(x = median_scaled_effect, color = type) +
  geom_density(size = 1) +
  theme_classic() +
  theme(aspect.ratio = 1) +
  scale_color_brewer(palette = 'Set1') +
  xlab('Median Z-score')
ggsave(here('figures', paste0(Sys.Date(), '_CP0036_enrichment.png')), width = 5, height = 4)
```


```{r cluster_validation}
dependency_cv <- validate_dependency(scaled_effects, clusters)
ccle_tidy_features <- load_ccle_features()
ccle_cv <- validate_ccle(ko_enrichment, clusters, ccle_tidy_features)
interesting_clusters <- c('1', '2', '3', '5', '11', '13', '14', '24', '25', '26', '27', '6', '4',
                          '10')
plot_cluster_aucs(clusters, ccle_cv, dependency_cv, label_clusters = c()) +
  xlab('Dependency AUC') +
  ylab('CCLE AUC')
ggsave(here('figures', paste0(Sys.Date(), 'cv_aucs.png')), width = 4, height = 4)
```

```{r CCLE validation}
summary_plots <- get_cluster_summary_plots(clusters, ccle_meta, embedding, ccle_cv, dependency_cv)
for(curr_cluster in interesting_clusters) {
  p <- summary_plots[[curr_cluster]]
  ggsave(here('figures', 'cluster_summaries', 
              paste0(Sys.Date(), '_cluster_', curr_cluster, '.png')), 
         width = 6, height = 4, p)
}
```

```{r temporal confounding}
achilles_meta <- load_achilles_meta()
cluster_achilles <- left_join(cluster_embedding, achilles_meta, 
                               by = c('DepMap_ID' = 'Arxspan ID')) 
plot_embedding(cluster_achilles, 'Late Harvest Date', alpha = 0.49, pch = 16) +
  scale_color_viridis_c(trans = 'date', option = 'B')
ggsave(here('figures', paste0(Sys.Date(), '_harvest_embedding.png')), width = 6, height = 4)
```

```{r}
ggplot(cluster_achilles) +
  aes(x = cluster, y = `Late Harvest Date`) +
  geom_bin2d() +
  scale_color_brewer(palette = 'Set1') +
  scale_fill_gradient(low = "gray90", high = "black") +
  theme_classic()
ggsave(here('figures', paste0(Sys.Date(), '_temporal_confounding_2d.png')), 
       width = 6, height = 5)
```

```{r remove and replot}
louvain_clusters <- generate_louvain_clusters(scaled_effects)
outlier_cells <- louvain_clusters %>%
  filter(cluster %in% c('11', '8', '5')) %>%
  select(DepMap_ID) %>%
  unlist() %>%
  as.character()
filtered_scaled_effects <- load_scaled_effects(filter_cells = outlier_cells)
filtered_embedding <- calculate_embedding(filtered_scaled_effects)
filtered_embedding_meta <- inner_join(filtered_embedding, ccle_meta)
plot_embedding(filtered_embedding_meta, 'primary_tissue', alpha = 0.9, 
               pch = 16, size = 2)
```

```{r}
filtered_embedding_achilles <- left_join(filtered_embedding, achilles_meta, 
                                         by = c('DepMap_ID' = 'Arxspan ID'))
plot_embedding(filtered_embedding_achilles, 'Late Harvest Date', alpha = 0.49, 
               pch = 16, size = 2) +
  scale_color_viridis_c(trans = 'date', option = 'B')
```


```{r}
# TO CODE: Traver's cells & NO cluster density plot,
# Future cell lines?
# TO DO: background! 
```

```{r}
FASN_enrichment <- scaled_effects %>%
  as.data.frame() %>%
  rownames_to_column('DepMap_ID') %>%
  as_tibble() %>%
  select('DepMap_ID', 'FASN (2194)')
embedding_meta_FASN <- embedding_meta %>%
  inner_join(FASN_enrichment) %>%
  arrange(abs(`FASN (2194)`))
plot_embedding(embedding_meta_FASN, 'FASN (2194)', alpha = 0.9,
               pch = 16, size = 2) +
  scale_color_gradient2() 
  
```

```{r}
embedding_meta_FASN_fe <- embedding_meta %>%
  inner_join(FASN_enrichment) %>%
  mutate(fe = stripped_cell_line_name %in% c('K562', 'NB4', 'MOLM13', 'THP1', 'MV411'), 
         ctl = stripped_cell_line_name %in% c('SUPT1', '697', 'NALM6', 'EOL1', 'L363', 'NOMO1')) %>%
  mutate(type = if_else(fe, 'FASN_fe', if_else(ctl, 'Control', ' Other'))) %>%
  arrange(type)
plot_embedding(embedding_meta_FASN_fe, 'type', alpha = 0.9,
               pch = 16, size = 2) +
  scale_color_manual(values = c('grey', '#d95f02', '#7570b3'))
```

```{r}
plot_embedding(embedding_meta_FASN, 'FASN (2194)', alpha = 1,
               pch = 16, size = 2) +
  scale_color_gradient2() +
  new_scale_color() +
  geom_label_repel(data = embedding_meta_FASN_fe %>% filter(type != ' Other'), 
                   aes(label = stripped_cell_line_name, color = type, 
                       fill = `FASN (2194)`), label.padding = 0.05, show.legend = FALSE,
                   point.padding = 0.1, min.segment.length = 0, 
                   box.padding = 0.5) +
  scale_fill_gradient2() +
  scale_color_manual(values = c('grey70', 'skyblue'))
ggsave(here('figures', paste0(Sys.Date(), 'FASN_fe.png')), width = 5, height = 4)
```

```{r}
embedding_meta_FASN_fe %>%
  inner_join(cluster_embedding) %>%
  filter(type != ' Other') %>%
  select(stripped_cell_line_name, DepMap_ID, type, cluster, primary_tissue, secondary_tissue, `FASN (2194)`) %>%
  arrange(type, cluster, `FASN (2194)`)
```

```{r}
cell_comparison <- scaled_effects %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column('gene') %>%
  as_tibble() %>%
  select(gene, `ACH-000294`, `ACH-000168`) 
ggplot(cell_comparison) +
  aes(x = `ACH-000294`, y = `ACH-000168`) +
  geom_pointdensity(pch = 16, alpha = 0.49) +
  scale_color_viridis_c() +
  coord_equal() +
  geom_label_repel(data = cell_comparison %>%
                     top_n(4, `ACH-000294`), 
                   aes(label = gene), min.segment.length = 0, label.padding = 0.3, 
                   size = 3, point.padding = 0.2) +
  ggpubr::stat_cor() +
  xlab('NB4') +
  ylab('NOMO1')
```

```{r}
PARP_enrichment <- scaled_effects %>%
  as.data.frame() %>%
  rownames_to_column('DepMap_ID') %>%
  as_tibble() %>%
  select('DepMap_ID', 'PARP1 (142)')
embedding_meta_PARP <- embedding_meta %>%
  inner_join(PARP_enrichment) %>%
  arrange(abs(`PARP1 (142)`))
plot_embedding(embedding_meta_PARP, 'PARP1 (142)', alpha = 0.9,
               pch = 16, size = 2) +
  scale_color_gradient2()
```

